import { T } from './theme';

export const S = {
  card: {
    background: T.white,
    borderRadius: 16,
    border: `1px solid ${T.borderLight}`,
    boxShadow: T.shadow,
    padding: 24,
    marginBottom: 16,
    transition: 'all 0.2s',
  },
  btn: (v = 'primary') => ({
    padding: '10px 20px',
    borderRadius: 10,
    border: v === 'outline' ? `2px solid ${T.primary}` : 'none',
    background: v === 'primary'
      ? `linear-gradient(135deg,${T.primary},${T.primaryDark})`
      : v === 'outline' ? T.white : T.primaryFaint,
    color: v === 'primary' ? T.white : T.primary,
    fontWeight: 600,
    fontSize: 14,
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
  }),
  btnSm: { padding: '6px 14px', fontSize: 13, borderRadius: 8 },
  input: {
    width: '100%',
    padding: '12px 16px',
    borderRadius: 10,
    border: `2px solid ${T.border}`,
    fontSize: 14,
    color: T.textDark,
    outline: 'none',
    background: T.white,
    transition: 'border-color 0.2s',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
  },
  tag: (a = false) => ({
    display: 'inline-flex',
    alignItems: 'center',
    padding: '6px 14px',
    borderRadius: 20,
    background: a ? T.primaryDark : T.primaryFaint,
    color: a ? T.white : T.primary,
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.2s',
    border: `1px solid ${a ? T.primaryDark : T.border}`,
    margin: '3px',
  }),
  avatar: (sz = 48) => ({
    width: sz,
    height: sz,
    borderRadius: '50%',
    background: `linear-gradient(135deg,${T.primary},${T.primaryLight})`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: T.white,
    fontWeight: 700,
    fontSize: sz * 0.38,
    flexShrink: 0,
    letterSpacing: '0.5px',
  }),
  flex: (g = 12) => ({
    display: 'flex',
    alignItems: 'center',
    gap: g,
  }),
  flexCol: (g = 12) => ({
    display: 'flex',
    flexDirection: 'column',
    gap: g,
  }),
  h1: {
    fontSize: 32,
    fontWeight: 700,
    color: T.primaryDark,
    margin: '0 0 8px',
    letterSpacing: '-0.5px',
  },
  h2: {
    fontSize: 22,
    fontWeight: 700,
    color: T.primaryDark,
    margin: '0 0 6px',
  },
  h3: {
    fontSize: 17,
    fontWeight: 600,
    color: T.textDark,
    margin: '0 0 4px',
  },
  muted: {
    color: T.textMuted,
    fontSize: 14,
  },
  grid2: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill,minmax(340px,1fr))',
    gap: 16,
  },
  divider: {
    border: 'none',
    borderTop: `1px solid ${T.borderLight}`,
    margin: '16px 0',
  },
};
